math_const = {'+': '+',
              '-': '-',
              '/': '/',
              '*': '*',
              '^': '**',
              '(': '(',
              ')': ')',
              'sin': 'math.sin',
              'cos': 'math.cos',
              'tg': 'math.tan',
              'ctg': '1/math.tan',
              'arcsin': 'math.asin',
              'arccos': 'math.acos',
              'arctg': 'math.atan',
              'sqrt': 'math.sqrt',
              'e': 'math.e',
              'pi': 'math.pi',
              **{str(x): str(x) for x in range(10)},
              '.': '.'}
